# Generated by Django 3.1.3 on 2020-11-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20201122_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank='', default=None, max_length=254, null=True),
        ),
    ]
