# Generated by Django 3.1.3 on 2020-11-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_auto_20201122_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Аффтар', 'verbose_name_plural': 'Аффтары'},
        ),
    ]
