# Generated by Django 3.1.3 on 2020-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_auto_20201122_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior Dev'), ('M', 'Middle Dev'), ('S', 'Senior Dev')], default='J', max_length=1),
        ),
    ]
