# Generated by Django 3.1.3 on 2020-11-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_article_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
