# Generated by Django 3.1.3 on 2020-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_category_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='pass_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
