# Generated by Django 3.1.3 on 2020-11-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_auto_20201128_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='pass_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
